# Generated by Django 4.0.6 on 2022-08-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComTradeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfCode', models.CharField(max_length=50)),
                ('yr', models.IntegerField()),
                ('period', models.IntegerField()),
                ('periodDesc', models.CharField(max_length=50)),
                ('aggrLevel', models.IntegerField()),
                ('IsLeaf', models.IntegerField()),
                ('rgCode', models.IntegerField()),
                ('rgDesc', models.CharField(max_length=50)),
                ('rtCode', models.IntegerField()),
                ('rtTitle', models.CharField(max_length=50)),
                ('rt3ISO', models.IntegerField()),
                ('ptCode', models.IntegerField()),
                ('ptTitle', models.CharField(max_length=50)),
                ('pt3ISO', models.IntegerField()),
                ('ptCode2', models.CharField(max_length=50)),
                ('ptTitle2', models.CharField(max_length=50)),
                ('pt3ISO2', models.CharField(max_length=50)),
                ('cstCode', models.CharField(max_length=50)),
                ('cstDesc', models.CharField(max_length=50)),
                ('motCode', models.CharField(max_length=50)),
                ('motDesc', models.CharField(max_length=50)),
                ('cmdCode', models.CharField(max_length=50)),
                ('cmdDescE', models.CharField(max_length=50)),
                ('qtCode', models.IntegerField()),
                ('qtDesc', models.IntegerField()),
                ('qtAltCode', models.IntegerField()),
                ('qtAltDesc', models.CharField(max_length=50)),
                ('TradeQuantity', models.IntegerField()),
                ('AltQuantity', models.IntegerField()),
                ('NetWeight', models.IntegerField()),
                ('GrossWeight', models.IntegerField()),
                ('TradeValue', models.IntegerField()),
                ('CIFValue', models.IntegerField()),
                ('FOBValue', models.IntegerField()),
                ('estCode', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
